spring:
  application:
    name: projectree
  datasource:
    # ?????? ?? URL (host, port, database_name ?? ??)
    url: jdbc:postgresql://localhost:5432/projectree
    username: postgre
    password: d107
    driver-class-name: org.postgresql.Driver

  jpa:
    # ?????? ??? ?? (Hibernate 6 ??? ?? ??)
    database-platform: org.hibernate.dialect.PostgreSQLDialect

    # ?????? ?? ? DDL ? ?? ?? ??
    # none, validate, update, create, create-drop ? ??
    hibernate:
      ddl-auto: update

    # ???? SQL ??? ??? ??
    show-sql: true
    properties:
      hibernate:
        # SQL? ??? ?? ??
        format_sql: true
        # ????? ???? ?? ???? ??
        use_sql_comments: true

# ?? ?? ??? ?? SQL ???? ?? (??? ? ??)
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE